### ISSUE TITLE
大一小白，摸索着把docker desktop安装后照readme执行，最后这样了，该如何解决

### ISSUE THREAD

**Issue by ssbcf** [rongchenlin/BiliBili-Lucky-Draw#21]
2024-02-07 22:07:27 dynamic_share-1  | WARNING:root:ip :127.0.0.1
2024-02-07 22:07:27 dynamic_share-1  | Traceback (most recent call last):
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/main.py", line 15, in <module>
2024-02-07 22:07:27 dynamic_share-1  | 127.0.0.1
2024-02-07 22:07:27 dynamic_share-1  | 127.0.0.1
2024-02-07 22:07:27 dynamic_share-1  | DataBase connect error,please check the db config.
2024-02-07 22:07:27 dynamic_share-1  |     do_search()
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/main.py", line 9, in do_search
2024-02-07 22:07:27 dynamic_share-1  |     SearchDynamicByUps(globals.my_user_id).init_search()
2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in __init__
2024-02-07 22:07:27 dynamic_share-1  |     db = init_db()
2024-02-07 22:07:27 dynamic_share-1  |          ^^^^^^^^^
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/dao/init_db.py", line 27, in init_db
2024-02-07 22:07:27 dynamic_share-1  |     db.selectDataBase(dbname)
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 38, in selectDataBase
2024-02-07 22:07:27 dynamic_share-1  |     self.con.select_db(DB_NAME)
2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^
2024-02-07 22:07:27 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'select_db'
2024-02-07 22:07:27 dynamic_share-1  | Exception ignored in: <function MysqldbHelper.__del__ at 0x7f1982f09940>
2024-02-07 22:07:27 dynamic_share-1  | Traceback (most recent call last):
2024-02-07 22:07:27 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 290, in __del__
2024-02-07 22:07:27 dynamic_share-1  |     self.cur.close()
2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^
2024-02-07 22:07:27 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'close'
2024-02-07 22:07:43 dynamic_share-1  | WARNING:root:ip :127.0.0.1
2024-02-07 22:07:43 dynamic_share-1  | Traceback (most recent call last):
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/main.py", line 15, in <module>
2024-02-07 22:07:43 dynamic_share-1  | 127.0.0.1
2024-02-07 22:07:43 dynamic_share-1  | 127.0.0.1
2024-02-07 22:07:43 dynamic_share-1  | DataBase connect error,please check the db config.
2024-02-07 22:07:43 dynamic_share-1  |     do_search()
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/main.py", line 9, in do_search
2024-02-07 22:07:43 dynamic_share-1  |     SearchDynamicByUps(globals.my_user_id).init_search()
2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in __init__
2024-02-07 22:07:43 dynamic_share-1  |     db = init_db()
2024-02-07 22:07:43 dynamic_share-1  |          ^^^^^^^^^
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/dao/init_db.py", line 27, in init_db
2024-02-07 22:07:43 dynamic_share-1  |     db.selectDataBase(dbname)
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 38, in selectDataBase
2024-02-07 22:07:43 dynamic_share-1  |     self.con.select_db(DB_NAME)
2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^
2024-02-07 22:07:43 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'select_db'
2024-02-07 22:07:43 dynamic_share-1  | Exception ignored in: <function MysqldbHelper.__del__ at 0x7fb3cbf99940>
2024-02-07 22:07:43 dynamic_share-1  | Traceback (most recent call last):
2024-02-07 22:07:43 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 290, in __del__
2024-02-07 22:07:43 dynamic_share-1  |     self.cur.close()
2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^
2024-02-07 22:07:43 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'close'

**Comment by rongchenlin** [comment]
建议IP不要填写127.0.0.1 ， 而是通过在cmd通过ipconfig查看IP并将其填入配置文件




林镕琛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rongchenlin/BiliBili-Lucky-Draw"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月7日(星期三) 晚上10:08
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[rongchenlin/BiliBili-Lucky-Draw] 大一小白，摸索着把docker desktop安装后照readme执行，最后这样了，该如何解决 (Issue #21)





 
2024-02-07 22:07:27 dynamic_share-1  | WARNING:root:ip :127.0.0.1
 2024-02-07 22:07:27 dynamic_share-1  | Traceback (most recent call last):
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/main.py", line 15, in 
 2024-02-07 22:07:27 dynamic_share-1  | 127.0.0.1
 2024-02-07 22:07:27 dynamic_share-1  | 127.0.0.1
 2024-02-07 22:07:27 dynamic_share-1  | DataBase connect error,please check the db config.
 2024-02-07 22:07:27 dynamic_share-1  |     do_search()
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/main.py", line 9, in do_search
 2024-02-07 22:07:27 dynamic_share-1  |     SearchDynamicByUps(globals.my_user_id).init_search()
 2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in init
 2024-02-07 22:07:27 dynamic_share-1  |     db = init_db()
 2024-02-07 22:07:27 dynamic_share-1  |          ^^^^^^^^^
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/dao/init_db.py", line 27, in init_db
 2024-02-07 22:07:27 dynamic_share-1  |     db.selectDataBase(dbname)
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 38, in selectDataBase
 2024-02-07 22:07:27 dynamic_share-1  |     self.con.select_db(DB_NAME)
 2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^
 2024-02-07 22:07:27 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'select_db'
 2024-02-07 22:07:27 dynamic_share-1  | Exception ignored in: <function MysqldbHelper.del at 0x7f1982f09940&gt;
 2024-02-07 22:07:27 dynamic_share-1  | Traceback (most recent call last):
 2024-02-07 22:07:27 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 290, in del
 2024-02-07 22:07:27 dynamic_share-1  |     self.cur.close()
 2024-02-07 22:07:27 dynamic_share-1  |     ^^^^^^^^^^^^^^
 2024-02-07 22:07:27 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'close'
 2024-02-07 22:07:43 dynamic_share-1  | WARNING:root:ip :127.0.0.1
 2024-02-07 22:07:43 dynamic_share-1  | Traceback (most recent call last):
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/main.py", line 15, in 
 2024-02-07 22:07:43 dynamic_share-1  | 127.0.0.1
 2024-02-07 22:07:43 dynamic_share-1  | 127.0.0.1
 2024-02-07 22:07:43 dynamic_share-1  | DataBase connect error,please check the db config.
 2024-02-07 22:07:43 dynamic_share-1  |     do_search()
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/main.py", line 9, in do_search
 2024-02-07 22:07:43 dynamic_share-1  |     SearchDynamicByUps(globals.my_user_id).init_search()
 2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in init
 2024-02-07 22:07:43 dynamic_share-1  |     db = init_db()
 2024-02-07 22:07:43 dynamic_share-1  |          ^^^^^^^^^
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/dao/init_db.py", line 27, in init_db
 2024-02-07 22:07:43 dynamic_share-1  |     db.selectDataBase(dbname)
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 38, in selectDataBase
 2024-02-07 22:07:43 dynamic_share-1  |     self.con.select_db(DB_NAME)
 2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^
 2024-02-07 22:07:43 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'select_db'
 2024-02-07 22:07:43 dynamic_share-1  | Exception ignored in: <function MysqldbHelper.del at 0x7fb3cbf99940&gt;
 2024-02-07 22:07:43 dynamic_share-1  | Traceback (most recent call last):
 2024-02-07 22:07:43 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 290, in del
 2024-02-07 22:07:43 dynamic_share-1  |     self.cur.close()
 2024-02-07 22:07:43 dynamic_share-1  |     ^^^^^^^^^^^^^^
 2024-02-07 22:07:43 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'close'

**Comment by rongchenlin** [comment]
建议IP不要填写127.0.0.1 ， 而是通过在cmd通过ipconfig查看IP并将其填入配置文件
![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/83388493/0b1bf618-4546-4588-84c8-2226b73fc2e9)

**Comment by ssbcf** [comment]
好像还有数据库的问题？？
2024-02-09 21:42:34 dynamic_share-1  | Traceback (most recent call last):
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/main.py", line 15, in <module>
2024-02-09 21:42:34 dynamic_share-1  | 172.17.208.1
2024-02-09 21:42:34 dynamic_share-1  | 172.17.208.1
2024-02-09 21:42:34 dynamic_share-1  | DataBase connect error,please check the db config.
2024-02-09 21:42:34 dynamic_share-1  |     do_search()
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/main.py", line 9, in do_search
2024-02-09 21:42:34 dynamic_share-1  |     SearchDynamicByUps(globals.my_user_id).init_search()
2024-02-09 21:42:34 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in __init__
2024-02-09 21:42:34 dynamic_share-1  |     db = init_db()
2024-02-09 21:42:34 dynamic_share-1  |          ^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/dao/init_db.py", line 27, in init_db
2024-02-09 21:42:34 dynamic_share-1  |     db.selectDataBase(dbname)
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 38, in selectDataBase
2024-02-09 21:42:34 dynamic_share-1  |     self.con.select_db(DB_NAME)
2024-02-09 21:42:34 dynamic_share-1  |     ^^^^^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'select_db'
2024-02-09 21:42:34 dynamic_share-1  | Exception ignored in: <function MysqldbHelper.__del__ at 0x7fdef176d940>
2024-02-09 21:42:34 dynamic_share-1  | Traceback (most recent call last):
2024-02-09 21:42:34 dynamic_share-1  |   File "/app/utils/mysql_operate.py", line 290, in __del__
2024-02-09 21:42:34 dynamic_share-1  |     self.cur.close()
2024-02-09 21:42:34 dynamic_share-1  |     ^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1  | AttributeError: 'NoneType' object has no attribute 'close'

**Comment by ssbcf** [comment]
> 建议IP不要填写127.0.0.1 ， 而是通过在cmd通过ipconfig查看IP并将其填入配置文件 ![image](https://private-user-images.githubusercontent.com/83388493/303009198-0b1bf618-4546-4588-84c8-2226b73fc2e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NTU3OTMsIm5iZiI6MTcwNzY1NTQ5MywicGF0aCI6Ii84MzM4ODQ5My8zMDMwMDkxOTgtMGIxYmY2MTgtNDU0Ni00NTg4LTg0YzgtMjIyNmI3M2ZjMmU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDEyNDQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NmUxNDNmYzk4ZjgzZmJiZWUyNDM1YTRiODgwNzE1MjZjZGRlMjczNjY2ZDc1OTJjZDM0YjJlYjRjMDU5YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8fY9wGztDsweSUERY8N2ZvDRXzzsQk5JsLn2CtJhzDE)
好像还有数据库的问题？？
2024-02-09 21:42:34 dynamic_share-1 | Traceback (most recent call last):
2024-02-09 21:42:34 dynamic_share-1 | File "/app/main.py", line 15, in
2024-02-09 21:42:34 dynamic_share-1 |
2024-02-09 21:42:34 dynamic_share-1 | ip我隐藏了
2024-02-09 21:42:34 dynamic_share-1 | DataBase connect error,please check the db config.
2024-02-09 21:42:34 dynamic_share-1 | do_search()
2024-02-09 21:42:34 dynamic_share-1 | File "/app/main.py", line 9, in do_search
2024-02-09 21:42:34 dynamic_share-1 | SearchDynamicByUps(globals.my_user_id).init_search()
2024-02-09 21:42:34 dynamic_share-1 | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1 | File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in init
2024-02-09 21:42:34 dynamic_share-1 | db = init_db()
2024-02-09 21:42:34 dynamic_share-1 | ^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1 | File "/app/dao/init_db.py", line 27, in init_db
2024-02-09 21:42:34 dynamic_share-1 | db.selectDataBase(dbname)
2024-02-09 21:42:34 dynamic_share-1 | File "/app/utils/mysql_operate.py", line 38, in selectDataBase
2024-02-09 21:42:34 dynamic_share-1 | self.con.select_db(DB_NAME)
2024-02-09 21:42:34 dynamic_share-1 | ^^^^^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1 | AttributeError: 'NoneType' object has no attribute 'select_db'
2024-02-09 21:42:34 dynamic_share-1 | Exception ignored in: <function MysqldbHelper.del at 0x7fdef176d940>
2024-02-09 21:42:34 dynamic_share-1 | Traceback (most recent call last):
2024-02-09 21:42:34 dynamic_share-1 | File "/app/utils/mysql_operate.py", line 290, in del
2024-02-09 21:42:34 dynamic_share-1 | self.cur.close()
2024-02-09 21:42:34 dynamic_share-1 | ^^^^^^^^^^^^^^
2024-02-09 21:42:34 dynamic_share-1 | AttributeError: 'NoneType' object has no attribute 'close'
