### ISSUE TITLE
centos 跑的，clone 了项目，docker 运行

### ISSUE THREAD

**Issue by tanzhijir-04** [rongchenlin/BiliBili-Lucky-Draw#33]
### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Docker

### 运行的python版本是?

python 3.7

### 复现步骤 🕹

在 centos 跑的，clone 了项目，docker 编译、运行，一开始没有安装 mysql、mariadb，后来安装了，

![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/149170904/fa3f1bc2-acea-418f-ae18-00822b14e132)

![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/149170904/b01c789a-6d2b-4980-91f3-bc5085c49313)

这是我的终端、服务器后台主页。

### 问题描述 😯

安装了 mariadb、mysql。在docker上跑的，这是cookie错误吗？因为我看到 SESSDATA 有两栏数据

### 终端日志 📒

```AttributeError: 'NoneType' object has no attribute 'close'
WARNING:root:ip :8.219.125.239
Traceback (most recent call last):
8.219.125.239
8.219.125.239
DataBase connect error,please check the db config.
  File "/app/main.py", line 15, in <module>
    do_search()
  File "/app/main.py", line 9, in do_search
    SearchDynamicByUps(globals.my_user_id).init_search()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in __init__
    db = init_db()
         ^^^^^^^^^
  File "/app/dao/init_db.py", line 27, in init_db
    db.selectDataBase(dbname)
  File "/app/utils/mysql_operate.py", line 38, in selectDataBase
    self.con.select_db(DB_NAME)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'select_db'
Exception ignored in: <function MysqldbHelper.__del__ at 0x7f7919745760>
Traceback (most recent call last):
  File "/app/utils/mysql_operate.py", line 290, in __del__
    self.cur.close()
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by rongchenlin** [comment]
请你提供一下.env文件配置信息（注意隐藏个人信息）

**Comment by qingniaoheyu** [comment]
遇到了同样问题：使用armbian跑的

log：
WARNING:root:ip :10.13.3.66
10.13.3.66
10.13.3.66
DataBase connect error,please check the db config.
Traceback (most recent call last):
  File "/app/main.py", line 15, in <module>
    do_search()
  File "/app/main.py", line 9, in do_search
    SearchDynamicByUps(globals.my_user_id).init_search()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 25, in __init__
    db = init_db()
         ^^^^^^^^^
  File "/app/dao/init_db.py", line 27, in init_db
    db.selectDataBase(dbname)
  File "/app/utils/mysql_operate.py", line 38, in selectDataBase
    self.con.select_db(DB_NAME)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'select_db'
Exception ignored in: <function MysqldbHelper.__del__ at 0x7fb7ade520>
Traceback (most recent call last):
  File "/app/utils/mysql_operate.py", line 290, in __del__
    self.cur.close()
    ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'close'

**Comment by qingniaoheyu** [comment]
.env设定如下

cookie_value=c4adfe62%2C1728055614%2C35bce%2A41CjDN6v2cxtNi5qGdzeaM_hJmItXSuz4Z3ITcKf_4pA2_M_RS4OwOiR8sAQ1FS0DPUFYSVjdoU0lfaldWVXJ1e(***隐藏部分cookie)
DB_HOST=10.13.3.66

# =========================== 固定配置信息 ===========================
my_user_id=test_id
max_checks=300
home_url=https://www.bilibili.com/
ignore_link=635932563238551585|869381005132169269|account|read|868970878687248419|883038425588957206
multi_users=test_id
# 执行e= multi single login_manual auto_login
do_type=login_manual
is_remove=N
remove_cnt=50
# ================= 数据库配置信息 =================
PORT=3206
MYSQL_DATABASE=luckybili
MYSQL_USER=luckybili
MYSQL_PASSWORD=luckybililuckybili
MYSQL_ROOT_PASSWORD=luckybililuckybili

# ================= 转发自定义信息 =================
share_content=一位支持你的粉丝正在抽奖|支持|抽奖啦!|顶!!|抽奖永不停止|棒棒哒|老板大气，参与抽奖！|真心不错啊|来了|冲|真不错
comment_content=棒棒哒，太喜欢啦!|这次真的爱了哟|好耶，参与一下。|超级幸运|冲吖|欧耶|大气|那就继续努力|我来抽个奖|转赞评支持|冲|想要
# 合集up主 你的工具人老公|_大锦鲤_|Carcinus_|闻不着味
ups=你的工具人老公|_大锦鲤_|Carcinus_|闻不着味

# ================= selenium驱动配置 =================
selenium_url=
# chromedriver版本：Online 或 Local
DRIVER_VERSION=Online
# =================================================================

# =========================== 可选配置信息 ===========================
# =================== 通知配置 ===================
notify_switch=N
FangTang_KEY=SCT172323T2wPuqkvImzZtZakj5slzlBZL
# =================================================================

**Comment by liupengai66** [comment]
如果用windows上的虚拟机怎么写ip
