### ISSUE TITLE
打开转发的up主主页是白屏

### ISSUE THREAD

**Issue by jack-lem** [rongchenlin/BiliBili-Lucky-Draw#37]
### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

python 3.7

### 问题描述 😯

![空白画面](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/34534288/83b724e0-fa3a-4927-8398-a85ae94c73dc)

### 终端日志 📒

![日志](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/34534288/2f31ff52-2f21-4f54-a16c-af25f73a39ae)

WARNING:root:ip :192.168.1.105
WARNING:root:创建数据库连接信息 :{'host': '192.168.1.105', 'port': 3206, 'user': 'luckybili', 'passwd': 'luckybililuckybili', 'charset': 'utf8', 'cursorclass': <class 'pymysql.cursors.DictCursor'>}
2024-06-03 21:18:46,019 - login_service.py - INFO - 启动登录模块
INFO:login_service.py:启动登录模块
2024-06-03 21:19:01,129 - login_service.py - INFO - 使用cookie自动登录成功！
INFO:login_service.py:使用cookie自动登录成功！
2024-06-03 21:19:19,396 - SearchDynamicByUps.py - ERROR - [searchFromFiftyUps 从“你的工具人老公”查找抽奖动态 出错 Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>
]
Traceback (most recent call last):
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 43, in searchFromFiftyUps
    first_dyn_element = ElementUtil.get_element_by_xpath(bro, chains, pathOne)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
    return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>

ERROR:SearchDynamicByUps.py:[searchFromFiftyUps 从“你的工具人老公”查找抽奖动态 出错 Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>
]
Traceback (most recent call last):
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 43, in searchFromFiftyUps
    first_dyn_element = ElementUtil.get_element_by_xpath(bro, chains, pathOne)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
    return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>

WARNING:root:ip :192.168.1.105
WARNING:root:创建数据库连接信息 :{'host': '192.168.1.105', 'port': 3206, 'user': 'luckybili', 'passwd': 'luckybililuckybili', 'charset': 'utf8', 'cursorclass': <class 'pymysql.cursors.DictCursor'>}
2024-06-03 21:19:32,107 - SearchDynamicByUps.py - ERROR - [searchFromBigFish 从“_大锦鲤_”查找抽奖动态 出错 Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>
]
Traceback (most recent call last):
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 72, in searchFromBigFish
    base_link_element = ElementUtil.get_element_by_xpath(bro, chains, pathOne)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
    return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>

ERROR:SearchDynamicByUps.py:[searchFromBigFish 从“_大锦鲤_”查找抽奖动态 出错 Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>
]
Traceback (most recent call last):
  File "/app/service/search_draw_dynamic_service/SearchDynamicByUps.py", line 72, in searchFromBigFish
    base_link_element = ElementUtil.get_element_by_xpath(bro, chains, pathOne)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
    return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5569e44bbe9a <unknown>
#1 0x5569e41a545c <unknown>
#2 0x5569e41f15b5 <unknown>
#3 0x5569e41f1671 <unknown>
#4 0x5569e4235f14 <unknown>
#5 0x5569e42144dd <unknown>
#6 0x5569e42332cc <unknown>
#7 0x5569e4214253 <unknown>
#8 0x5569e41e41c7 <unknown>
#9 0x5569e41e4b3e <unknown>
#10 0x5569e44822db <unknown>
#11 0x5569e4486387 <unknown>
#12 0x5569e446ee0e <unknown>
#13 0x5569e4486e52 <unknown>
#14 0x5569e44537af <unknown>
#15 0x5569e44ab188 <unknown>
#16 0x5569e44ab35b <unknown>
#17 0x5569e44bafcc <unknown>
#18 0x7f24a8e5eac3 <unknown>

**Comment by ZRHann** [comment]
应该跟cookie有关，扫码登录是可以的，用login_by_cookie不行，login_by_cookie2可以。感觉是只有SESSDATA不够。

**Comment by Gnlop** [comment]
一样的错误 求解

**Comment by fyt2001** [comment]
login_by_cookie2需要的./cookie/test_id.txt没有，需要怎么配置
