### ISSUE TITLE
无法点赞，关注，评论，转发动态。

### ISSUE THREAD

**Issue by QingXuer** [rongchenlin/BiliBili-Lucky-Draw#43]
### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的python版本是?

other

### 复现步骤 🕹

正常运行。

### 问题描述 😯

正常运行能读取到转发的动态，但是无法点赞，关注，评论，转发。
python版本Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
类似issue：https://github.com/rongchenlin/BiliBili-Lucky-Draw/issues/42#issue-2385313279

### 终端日志 📒

```log
2024-08-22 00:18:35 dynamic_share-1  | INFO:login_service.py:使用cookie自动登录成功！
2024-08-22 00:17:20 bili-db          | 2024-08-21 16:17:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.44-1.el7 started.
2024-08-22 00:17:22 bili-db          | 2024-08-21 16:17:22+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2024-08-22 00:17:22 bili-db          | 2024-08-21 16:17:22+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.44-1.el7 started.
2024-08-22 00:17:22 bili-db          | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.704026Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.711636Z 0 [Note] mysqld (mysqld 5.7.44) starting as process 1 ...
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.718102Z 0 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719966Z 0 [Note] InnoDB: PUNCH HOLE support available
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719991Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719994Z 0 [Note] InnoDB: Uses event mutexes
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719996Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719997Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.719998Z 0 [Note] InnoDB: Using Linux native AIO
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.720668Z 0 [Note] InnoDB: Number of pools: 1
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.721952Z 0 [Note] InnoDB: Using CPU crc32 instructions
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.723410Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.728129Z 0 [Note] InnoDB: Completed initialization of buffer pool
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.729987Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.781781Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.961129Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2024-08-22 00:17:22 bili-db          | 2024-08-21T16:17:22.963535Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.050161Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.053399Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.053432Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.054362Z 0 [Note] InnoDB: 5.7.44 started; log sequence number 12247964
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.055122Z 0 [Note] Plugin 'FEDERATED' is disabled.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.056835Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.107306Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.107331Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.107335Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.107335Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.115274Z 0 [Warning] CA certificate ca.pem is self signed.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.116650Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.122653Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.122705Z 0 [Note] IPv6 is available.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.122718Z 0 [Note]   - '::' resolves to '::';
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.122729Z 0 [Note] Server socket created on IP: '::'.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.126104Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.149765Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240821 16:17:23
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.737742Z 0 [Note] Event Scheduler: Loaded 0 events
2024-08-22 00:17:23 bili-db          | 2024-08-21T16:17:23.738096Z 0 [Note] mysqld: ready for connections.
2024-08-22 00:17:23 bili-db          | Version: '5.7.44'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2024-08-22 00:18:45 bili-selenium    | 16:18:45.030 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-08-22 00:19:00 bili-selenium    | 16:19:00.033 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-08-22 00:19:15 bili-selenium    | 16:19:15.037 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-08-22 00:19:17 dynamic_share-1  | 2024-08-21 16:19:17,467 - share_one_dynamic.py - ERROR - [click_share 点击“分享” 出错 Message: 
2024-08-22 00:19:17 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:17 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | ]
2024-08-22 00:19:17 dynamic_share-1  | Traceback (most recent call last):
2024-08-22 00:19:17 dynamic_share-1  |   File "/app/service/share_service/share_one_dynamic.py", line 163, in click_share
2024-08-22 00:19:17 dynamic_share-1  |     share_text_old = ElementUtil.get_element_by_xpath(bro, chains,
2024-08-22 00:19:17 dynamic_share-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:17 dynamic_share-1  |   File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
2024-08-22 00:19:17 dynamic_share-1  |     return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
2024-08-22 00:19:17 dynamic_share-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:17 dynamic_share-1  |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
2024-08-22 00:19:17 dynamic_share-1  |     raise TimeoutException(message, screen, stacktrace)
2024-08-22 00:19:17 dynamic_share-1  | selenium.common.exceptions.TimeoutException: Message: 
2024-08-22 00:19:17 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:17 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | 
2024-08-22 00:19:17 dynamic_share-1  | ERROR:share_one_dynamic.py:[click_share 点击“分享” 出错 Message: 
2024-08-22 00:19:17 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:17 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | ]
2024-08-22 00:19:17 dynamic_share-1  | Traceback (most recent call last):
2024-08-22 00:19:17 dynamic_share-1  |   File "/app/service/share_service/share_one_dynamic.py", line 163, in click_share
2024-08-22 00:19:17 dynamic_share-1  |     share_text_old = ElementUtil.get_element_by_xpath(bro, chains,
2024-08-22 00:19:17 dynamic_share-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:17 dynamic_share-1  |   File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
2024-08-22 00:19:17 dynamic_share-1  |     return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
2024-08-22 00:19:17 dynamic_share-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:17 dynamic_share-1  |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
2024-08-22 00:19:17 dynamic_share-1  |     raise TimeoutException(message, screen, stacktrace)
2024-08-22 00:19:17 dynamic_share-1  | selenium.common.exceptions.TimeoutException: Message: 
2024-08-22 00:19:17 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:17 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:17 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:17 dynamic_share-1  | 
2024-08-22 00:19:17 dynamic_share-1  | 2024-08-21 16:19:17,492 - share_one_dynamic.py - ERROR - share_one 转发单条动态主流程 出错url : https://t.bilibili.com/966213082942537748
2024-08-22 00:19:17 dynamic_share-1  | ERROR:share_one_dynamic.py:share_one 转发单条动态主流程 出错url : https://t.bilibili.com/966213082942537748
2024-08-22 00:19:17 dynamic_share-1  | 2024-08-21 16:19:17,494 - share_one_dynamic.py - INFO - 单条动态转发--执行结束
2024-08-22 00:19:17 dynamic_share-1  | INFO:share_one_dynamic.py:单条动态转发--执行结束
2024-08-22 00:19:30 bili-selenium    | 16:19:30.042 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-08-22 00:19:45 bili-selenium    | 16:19:45.048 WARN [ThrottlingLogger.doLog] - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
2024-08-22 00:19:55 dynamic_share-1  | 2024-08-21 16:19:55,317 - share_one_dynamic.py - ERROR - [click_share 点击“分享” 出错 Message: 
2024-08-22 00:19:55 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:55 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | ]
2024-08-22 00:19:55 dynamic_share-1  | Traceback (most recent call last):
2024-08-22 00:19:55 dynamic_share-1  |   File "/app/service/share_service/share_one_dynamic.py", line 163, in click_share
2024-08-22 00:19:55 dynamic_share-1  |     share_text_old = ElementUtil.get_element_by_xpath(bro, chains,
2024-08-22 00:19:55 dynamic_share-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:55 dynamic_share-1  |   File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
2024-08-22 00:19:55 dynamic_share-1  |     return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
2024-08-22 00:19:55 dynamic_share-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:55 dynamic_share-1  |   File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
2024-08-22 00:19:55 dynamic_share-1  |     raise TimeoutException(message, screen, stacktrace)
2024-08-22 00:19:55 dynamic_share-1  | selenium.common.exceptions.TimeoutException: Message: 
2024-08-22 00:19:55 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:55 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | 
2024-08-22 00:19:55 dynamic_share-1  | ERROR:share_one_dynamic.py:[click_share 点击“分享” 出错 Message: 
2024-08-22 00:19:55 dynamic_share-1  | Stacktrace:
2024-08-22 00:19:55 dynamic_share-1  | #0 0x55d28e04a6ca <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #1 0x55d28dd1b600 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #2 0x55d28dd6abcb <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #3 0x55d28dd6aeb1 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #4 0x55d28ddaeb24 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #5 0x55d28dd8d8cd <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #6 0x55d28ddac04a <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #7 0x55d28dd8d643 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #8 0x55d28dd5dd31 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #9 0x55d28dd5e79e <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #10 0x55d28e01225b <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #11 0x55d28e0161f2 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #12 0x55d28dfff615 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #13 0x55d28e016d82 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #14 0x55d28dfe425f <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #15 0x55d28e039e68 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #16 0x55d28e03a040 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #17 0x55d28e04949c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #18 0x7fcbd2511a94 <unknown>
2024-08-22 00:19:55 dynamic_share-1  | #19 0x7fcbd259ec3c <unknown>
2024-08-22 00:19:55 dynamic_share-1  | ]
2024-08-22 00:19:55 dynamic_share-1  | Traceback (most recent call last):
2024-08-22 00:19:55 dynamic_share-1  |   File "/app/service/share_service/share_one_dynamic.py", line 163, in click_share
2024-08-22 00:19:55 dynamic_share-1  |     share_text_old = ElementUtil.get_element_by_xpath(bro, chains,
2024-08-22 00:19:55 dynamic_share-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-22 00:19:55 dynamic_share-1  |   File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
2024-08-22 00:19:55 dynamic_share-1  |     return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
2024-08-22 00:19:55 dynamic_share-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
还有更多类似的超过65536，故直截取这一小段。

**Comment by imysen** [comment]
能运行但是不能转发，有遇到相同问题的小伙伴可以一起看下 ：） 非常感谢 
会打开转发的对话框但是不会点击“发布”（我个人推测是来不及点击网页就跳转了，不确定是否是这个原因）ng

```log
#18 0x75c786416a94 <unknown>
#19 0x75c7864a3a34 __clone
]
Traceback (most recent call last):
  File "/app/service/share_service/share_one_dynamic.py", line 107, in click_like
    like_btn_old = ElementUtil.get_element_by_xpath(bro, chains, path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/utils/webdriver_util.py", line 21, in get_element_by_xpath
    return WebDriverWait(bro, 10).until(EC.element_to_be_clickable((By.XPATH, path)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55cfe47f86ca <unknown>
#1 0x55cfe44c9600 <unknown>
#2 0x55cfe4518bcb <unknown>
#3 0x55cfe4518eb1 <unknown>
#4 0x55cfe455cb24 <unknown>
#5 0x55cfe453b8cd <unknown>
#6 0x55cfe455a04a <unknown>
#7 0x55cfe453b643 <unknown>
#8 0x55cfe450bd31 <unknown>
#9 0x55cfe450c79e <unknown>
#10 0x55cfe47c025b <unknown>
#11 0x55cfe47c41f2 <unknown>
#12 0x55cfe47ad615 <unknown>
#13 0x55cfe47c4d82 <unknown>
#14 0x55cfe479225f <unknown>
#15 0x55cfe47e7e68 <unknown>
#16 0x55cfe47e8040 <unknown>
#17 0x55cfe47f749c <unknown>
#18 0x75c786416a94 <unknown>
#19 0x75c7864a3a34 __clone

2024-08-22 07:06:38,565 - share_one_dynamic.py - ERROR - share_one 转发单条动态主流程 出错url : https://t.bilibili.com/967577830303989765
ERROR:share_one_dynamic.py:share_one 转发单条动态主流程 出错url : https://t.bilibili.com/967577830303989765
2024-08-22 07:06:38,565 - share_one_dynamic.py - INFO - 单条动态转发--执行结束
INFO:share_one_dynamic.py:单条动态转发--执行结束
2024-08-22 07:06:38,753 - share_one_dynamic.py - ERROR - share_one 转发单条动态主流程 出错url : https://t.bilibili.com/967580325670551608
ERROR:share_one_dynamic.py:share_one 转发单条动态主流程 出错url : https://t.bilibili.com/967580325670551608
2024-08-22 07:06:38,753 - share_one_dynamic.py - INFO - 单条动态转发--执行结束
```

```
