### ISSUE TITLE
docker 实例启动之后cookie无法获取

### ISSUE THREAD

**Issue by guiyu** [rongchenlin/BiliBili-Lucky-Draw#7]
按您的方法build后up实例，发现ip:5555无法访问，docker ps后发现bilibililuckydraw_gen_cookie 这个镜像似乎没拉起来？
<img width="1705" alt="image" src="https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/635471/98a8af16-e8f7-4728-a9df-92bbb2e1cbbb">

请问这是造成我无法访问的原因吗？

**Comment by rongchenlin** [comment]
服务器的端口是否打开了？

**Comment by guiyu** [comment]
重新build了一遍镜像，打开了端口。这次出现错误信息log了，应该是mysql的密码配的不对，请问这个密码在.env里配置了之后，还需要再哪写入登陆一次？
<img width="1416" alt="image" src="https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/635471/d2927d01-1636-4361-9079-2bc663becb2f">

**Comment by rongchenlin** [comment]
![image](https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/83388493/48198134-fb9f-4a26-acaa-09a3d4c52f59)
这里 不要用回环地址127.0.0.1，尝试用真实地址试试

**Comment by guiyu** [comment]
多谢，但是问题依然还是存在。
<img width="1729" alt="image" src="https://github.com/rongchenlin/BiliBili-Lucky-Draw/assets/635471/3d1fd5ab-f929-4bbd-a834-d8d0cbd59c73">


是否与我mysql设置的用户名和密码有关？我设置的是随机的密码。

**Comment by guiyu** [comment]
[root@iZ2zei2r2mu7vxpc4ir1sfZ BiliBili-Lucky-Draw]# docker-compose up
Recreating bilibililuckydraw_selenium_1 ... 
Recreating bilibililuckydraw_selenium_1 ... done
Recreating bilibililuckydraw_dynamic_share_1 ... 
Recreating bilibililuckydraw_gen_cookie_1 ... 
Recreating bilibililuckydraw_search_user_1 ... done
Attaching to bilibililuckydraw_db_1, bilibililuckydraw_selenium_1, bilibililuckydraw_dynamic_share_1, bilibililuckydraw_gen_cookie_1, bilibililuckydraw_search_user_1
db_1             | 2023-06-28 16:17:06+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.42-1.el7 started.
db_1             | 2023-06-28 16:17:07+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1             | 2023-06-28 16:17:07+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.7.42-1.el7 started.
db_1             | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
db_1             | 2023-06-28T16:17:07.827964Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db_1             | 2023-06-28T16:17:07.832236Z 0 [Note] mysqld (mysqld 5.7.42) starting as process 1 ...
db_1             | 2023-06-28T16:17:07.841910Z 0 [Note] InnoDB: PUNCH HOLE support available
db_1             | 2023-06-28T16:17:07.842115Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1             | 2023-06-28T16:17:07.842132Z 0 [Note] InnoDB: Uses event mutexes
db_1             | 2023-06-28T16:17:07.842139Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db_1             | 2023-06-28T16:17:07.842145Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
db_1             | 2023-06-28T16:17:07.842151Z 0 [Note] InnoDB: Using Linux native AIO
db_1             | 2023-06-28T16:17:07.843728Z 0 [Note] InnoDB: Number of pools: 1
db_1             | 2023-06-28T16:17:07.844730Z 0 [Note] InnoDB: Using CPU crc32 instructions
db_1             | 2023-06-28T16:17:07.859091Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db_1             | 2023-06-28T16:17:07.885508Z 0 [Note] InnoDB: Completed initialization of buffer pool
db_1             | 2023-06-28T16:17:07.889879Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1             | 2023-06-28T16:17:07.903482Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db_1             | 2023-06-28T16:17:07.911631Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12236816
db_1             | 2023-06-28T16:17:07.911696Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12236825
db_1             | 2023-06-28T16:17:07.911707Z 0 [Note] InnoDB: Database was not shutdown normally!
db_1             | 2023-06-28T16:17:07.911713Z 0 [Note] InnoDB: Starting crash recovery.
db_1             | 2023-06-28T16:17:08.059369Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1             | 2023-06-28T16:17:08.059408Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1             | 2023-06-28T16:17:08.059505Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1             | 2023-06-28T16:17:08.099008Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1             | 2023-06-28T16:17:08.100137Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db_1             | 2023-06-28T16:17:08.100185Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db_1             | 2023-06-28T16:17:08.100553Z 0 [Note] InnoDB: Waiting for purge to start
db_1             | 2023-06-28T16:17:08.150898Z 0 [Note] InnoDB: 5.7.42 started; log sequence number 12236825
db_1             | 2023-06-28T16:17:08.151494Z 0 [Note] Plugin 'FEDERATED' is disabled.
db_1             | 2023-06-28T16:17:08.164648Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db_1             | 2023-06-28T16:17:08.164693Z 0 [Note] Skipping generation of SSL certificates as certificate files are present in data directory.
db_1             | 2023-06-28T16:17:08.164700Z 0 [Warning] A deprecated TLS version TLSv1 is enabled. Please use TLSv1.2 or higher.
db_1             | 2023-06-28T16:17:08.164704Z 0 [Warning] A deprecated TLS version TLSv1.1 is enabled. Please use TLSv1.2 or higher.
db_1             | 2023-06-28T16:17:08.165638Z 0 [Warning] CA certificate ca.pem is self signed.
db_1             | 2023-06-28T16:17:08.165695Z 0 [Note] Skipping generation of RSA key pair as key files are present in data directory.
db_1             | 2023-06-28T16:17:08.166015Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db_1             | 2023-06-28T16:17:08.166099Z 0 [Note] IPv6 is available.
db_1             | 2023-06-28T16:17:08.166114Z 0 [Note]   - '::' resolves to '::';
db_1             | 2023-06-28T16:17:08.166155Z 0 [Note] Server socket created on IP: '::'.
db_1             | 2023-06-28T16:17:08.166805Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1             | 2023-06-28T16:17:08.169812Z 0 [Note] InnoDB: Buffer pool(s) load completed at 230628 16:17:08
db_1             | 2023-06-28T16:17:08.172381Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1             | 2023-06-28T16:17:08.197433Z 0 [Note] Event Scheduler: Loaded 0 events
db_1             | 2023-06-28T16:17:08.197831Z 0 [Note] mysqld: ready for connections.
db_1             | Version: '5.7.42'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
selenium_1       | 2023-06-28 16:17:07,171 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing
selenium_1       | 2023-06-28 16:17:07,182 INFO RPC interface 'supervisor' initialized
selenium_1       | 2023-06-28 16:17:07,182 CRIT Server 'unix_http_server' running without any HTTP authentication checking
selenium_1       | 2023-06-28 16:17:07,183 INFO supervisord started with pid 8
selenium_1       | 2023-06-28 16:17:08,188 INFO spawned: 'xvfb' with pid 10
selenium_1       | 2023-06-28 16:17:08,194 INFO spawned: 'vnc' with pid 11
selenium_1       | 2023-06-28 16:17:08,202 INFO spawned: 'novnc' with pid 12
selenium_1       | 2023-06-28 16:17:08,229 INFO spawned: 'selenium-standalone' with pid 14
selenium_1       | Setting up SE_NODE_GRID_URL...
selenium_1       | 2023-06-28 16:17:08,327 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1       | 2023-06-28 16:17:08,327 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1       | 2023-06-28 16:17:08,328 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
selenium_1       | 2023-06-28 16:17:08,328 INFO success: selenium-standalone entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
gen_cookie_1     | Traceback (most recent call last):
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
gen_cookie_1     |     conn = connection.create_connection(
gen_cookie_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
gen_cookie_1     |     raise err
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
gen_cookie_1     |     sock.connect(sa)
gen_cookie_1     | ConnectionRefusedError: [Errno 111] Connection refused
gen_cookie_1     | 
gen_cookie_1     | During handling of the above exception, another exception occurred:
gen_cookie_1     | 
gen_cookie_1     | Traceback (most recent call last):
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
gen_cookie_1     |     httplib_response = self._make_request(
gen_cookie_1     |                        ^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
gen_cookie_1     |     conn.request(method, url, **httplib_request_kw)
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
gen_cookie_1     |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
gen_cookie_1     |   File "/usr/local/lib/python3.11/http/client.py", line 1286, in request
gen_cookie_1     |     self._send_request(method, url, body, headers, encode_chunked)
gen_cookie_1     |   File "/usr/local/lib/python3.11/http/client.py", line 1332, in _send_request
gen_cookie_1     |     self.endheaders(body, encode_chunked=encode_chunked)
gen_cookie_1     |   File "/usr/local/lib/python3.11/http/client.py", line 1281, in endheaders
gen_cookie_1     |     self._send_output(message_body, encode_chunked=encode_chunked)
gen_cookie_1     |   File "/usr/local/lib/python3.11/http/client.py", line 1041, in _send_output
selenium_1       | Selenium Grid Standalone configuration: 
gen_cookie_1     |     self.send(msg)
gen_cookie_1     |   File "/usr/local/lib/python3.11/http/client.py", line 979, in send
gen_cookie_1     |     self.connect()
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
gen_cookie_1     |     conn = self._new_conn()
gen_cookie_1     |            ^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
gen_cookie_1     |     raise NewConnectionError(
gen_cookie_1     | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f295a6f7c90>: Failed to establish a new connection: [Errno 111] Connection refused
gen_cookie_1     | 
gen_cookie_1     | During handling of the above exception, another exception occurred:
gen_cookie_1     | 
gen_cookie_1     | Traceback (most recent call last):
gen_cookie_1     |   File "/app/login_gen_cookie.py", line 34, in <module>
gen_cookie_1     |     bro, chains = init_webdriver_for_gen_cookie()
gen_cookie_1     |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/app/utils/selenium_util.py", line 29, in init_webdriver_for_gen_cookie
gen_cookie_1     |     driver = webdriver.Remote(
gen_cookie_1     |              ^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 266, in __init__
gen_cookie_1     |     self.start_session(capabilities, browser_profile)
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 357, in start_session
gen_cookie_1     |     response = self.execute(Command.NEW_SESSION, parameters)
gen_cookie_1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 416, in execute
gen_cookie_1     |     response = self.command_executor.execute(driver_command, params)
gen_cookie_1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 398, in execute
gen_cookie_1     |     return self._request(command_info[0], url, body=data)
gen_cookie_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 420, in _request
gen_cookie_1     |     resp = self._conn.request(method, url, body=body, headers=headers)
gen_cookie_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 78, in request
gen_cookie_1     |     return self.request_encode_body(
gen_cookie_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/request.py", line 170, in request_encode_body
gen_cookie_1     |     return self.urlopen(method, url, **extra_kw)
gen_cookie_1     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 376, in urlopen
gen_cookie_1     |     response = conn.urlopen(method, u.request_uri, **kw)
gen_cookie_1     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
gen_cookie_1     |     return self.urlopen(
gen_cookie_1     |            ^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
gen_cookie_1     |     return self.urlopen(
gen_cookie_1     |            ^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 815, in urlopen
gen_cookie_1     |     return self.urlopen(
gen_cookie_1     |            ^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
gen_cookie_1     |     retries = retries.increment(
gen_cookie_1     |               ^^^^^^^^^^^^^^^^^^
gen_cookie_1     |   File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
gen_cookie_1     |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
gen_cookie_1     | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='59.110.138.195', port=5555): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f295a6f7c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
selenium_1       | [network]
selenium_1       | relax-checks = true
selenium_1       | 
selenium_1       | [node]
selenium_1       | session-timeout = "300"
selenium_1       | override-max-sessions = true
selenium_1       | detect-drivers = false
selenium_1       | drain-after-session-count = 0
selenium_1       | max-sessions = 5
selenium_1       | 
selenium_1       | [[node.driver-configuration]]
selenium_1       | display-name = "chrome"
selenium_1       | stereotype = '{"browserName": "chrome", "browserVersion": "114.0", "platformName": "Linux"}'
selenium_1       | max-sessions = 5
selenium_1       | 
selenium_1       | Starting Selenium Grid Standalone...
selenium_1       | Tracing is disabled
dynamic_share_1  | WARNING:root:未登录，或者Cookie失效，请重新登录, waiting...
search_user_1    | WARNING:root:未登录，或者Cookie失效，请重新登录, waiting...

**Comment by guiyu** [comment]
@rongchenlin 我感觉还是mysql的账号配置问题。
我看log里使用的是mysql
db_1 | 2023-06-28 16:17:07+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'

但我在.env里配置的并不是这个账号，请问是这个原因吗？如果是请告知我.env里mysql用户名密码配置的规则。
